# Generated by Django 4.2.5 on 2024-01-18 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="location",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="type",
        ),
    ]
