# Generated by Django 4.2.5 on 2024-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canteen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=1, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
