# Generated by Django 4.2.5 on 2023-10-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.order'),
        ),
    ]
